[package]
name = "aoc_2015_day_12"
version = "1.0.0"
edition = "2021"
description = "Advent of Code 2015-12"
repository = "https://github.com/alyx-dev/advent-of-code"
license = "MIT"

[dependencies]
aoc = { path = "../.." }
regex = { version = "1" }
serde_json = { version = "1" }
