[package]
name = "aoc_2015_day_09"
version = "1.0.0"
edition = "2021"
description = "Advent of Code 2015-9"
repository = "https://github.com/alyx-dev/advent-of-code"
license = "MIT"

[dependencies]
aoc = { path = "../.." }
itertools = { version = "0.10" }
