[package]
name = "aoc_2016_day_13"
version = "1.0.0"
edition = "2021"
description = "Advent of Code 2016-13"
repository = "https://github.com/alyx-dev/advent-of-code"
license = "MIT"

[dependencies]
aoc = { path = "../.." }
