[package]
name = "aoc_2018_day_22"
version = "1.0.0"
edition = "2021"
description = "Advent of Code 2018-22"
repository = "https://github.com/alyx-dev/advent-of-code"
license = "MIT"

[dependencies]
aoc = { path = "../.." }
